name: Build Operator Images

on:
  workflow_dispatch: {}
  push:
    tags:
      - v*

permissions: read-all

jobs:
  Upload:
    permissions:
      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#authenticating-to-package-registries-on-github
      packages: write
    strategy:
      matrix:
        # arch: [ amd64, arm64 ]
        image:
          [ chaosblade-operator ]
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    runs-on: ubuntu-20.04
    steps:
      - name: Extract Image Tag
        id: image_tag
        shell: bash
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          echo "::set-output name=image_tag::$(echo $IMAGE_TAG)"

      - name: echo arch
        run: echo arch = $(arch)

      - uses: actions/checkout@v2

      - name: Set Up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go


      - name: Build Image
        run: |
          make docker-build-arm64
        #  make docker-build
          


      # - name: Upload Image
      #   run: |
      #     make push_image
